name: Build Windows EXE

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install pkg globally
        run: npm install -g pkg@5.8.0

      - name: Build EXE (Windows x64)
        run: pkg . --targets node18-win-x64 --output unu-training.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: unu-training-exe
          path: unu-training.exe
