name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g pkg
      - run: pkg . --targets node18-win-x64 --output unu-helper.exe
      - uses: actions/upload-artifact@v4
        with:
          name: unu-helper-windows
          path: unu-helper.exe
